import random
# importing the number generation library
numGames = int(input("How many games: "))
# how many guesses
for i in range(0, numGames):
# this is the number of guesses
    print('Start Guessing')
    # this is the variable for the random number
    # that is generated by the 'random' library
    hiddenNumber = random.randint(1,50)
    # the variable for the number of times
    # the player has guessed
    userGuess = 0

    while not userGuess == hiddenNumber:
        # while loop that will only end when the player inputs
        # the right number
        userGuess = int(input('Guess a number: '))
        # this ask the player to input the number of guesses
        if userGuess > hiddenNumber:
            print('Too high')
        # print if the guess is too high
        elif userGuess < hiddenNumber:
            print('Too low')
        #print if the guess is too low
        else:
            print("that's right")
        # else it understands that it is the right number
